name: CI
run-name: ${{ github.actor }} pushed to the repository
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tests and lint  
        run: | 
          cargo clippy -- -D -warnings
          cargo check
          cargo test